### ISSUE TITLE
Is new recaptcha (i am not a robot tick) compatible with ∞²?

### ISSUE THREAD

**Issue by xenu-cf** [tomslominski/infinity-squared#10]
Is [new recaptcha](http://recaptcha.com) (i am not a robot verification via tick) compatible with ∞² (Infinity Squared)? 

if not, how do i add support for it?

**Comment by tomslominski** [comment]
I don't see why not, although I haven't personally looked into integrating it. However, have you tried using the [no-captcha branch](https://github.com/tomslominski/infinity-squared/tree/no-captcha) of IS? This simply uses a hidden field which bots tend to automatically fill out, but humans cannot see. It should prevent spam and is even easier and less intrusive than the new reCAPTCHA.

**Comment by xenu-cf** [comment]
Tried it. not really effective (get maby only a little less than a standard established YOURLS install without protection)

**Comment by tomslominski** [comment]
I've just whipped up a quick something... Check out the [nocaptcha-recaptcha branch](https://github.com/tomslominski/infinity-squared/tree/nocaptcha-recaptcha) and see if that works. I've not tested it very well, so beware!

**Comment by tomslominski** [comment]
The tick captcha is now being merged into the master branch and will be available in the next release.

**Comment by tvvocold** [comment]
OK,can i use the master branch now or when will it released?

**Comment by tomslominski** [comment]
I'd suggest waiting until it's released.

**Comment by tvvocold** [comment]
Plz ping me if you release it.

**Comment by tomslominski** [comment]
Feel free to test the master branch now. There's been quite a lot of changes in this release so I'm waiting for someone to test it before I release it in case there's any major issues. But I'm not expecting to make any more changes other than bug fixes.
