### ISSUE TITLE
No-CAPTCHA reCAPTCHA convert?

### ISSUE THREAD

**Issue by xenu-cf** [tomslominski/infinity-squared#17]
Is there an easy way to convert from standard no-captcha (secret bot form) to new reCAPTCHA without having me to re-edit my custom index.php and results.php?

**Comment by tomslominski** [comment]
No. You'll need to either copy your changes to the latest version of Infinity Squared in the master branch or basically implement the new reCAPTCHA yourself based on information provided by Google.

**Comment by xenu-cf** [comment]
Well, Can I at least have the old No-CAPTCHA branch again to compare?

**Comment by tomslominski** [comment]
I've restored the branch for you. https://github.com/tomslominski/infinity-squared/tree/nocaptcha-recaptcha

**Comment by xenu-cf** [comment]
well, by the old branch, i meant the nocaptcha secret bot form VS reCAPTCHA

**Comment by tomslominski** [comment]
It's cool. This is the last commit before the new reCAPTCHA was merged, so hopefully this will help? https://github.com/tomslominski/infinity-squared/tree/ff9d158626e1981bd381cda4e9ccf791b75d4dc0

**Comment by Brahmachari** [comment]
Hi, I have implemented your public interface - seams to be the best and nicest around the world!  :-))
On 6 Apr. you wrote: "...implement the new reCAPTCHA yourself based on information provided by Google."

Even with the examples provided, your recaptchalib.php is so genious that I have no chance to implement the new codes. It can not just be done with cut and paste. Please, would you be so kind and provide an update.

Cross fingers you have time for that.  ;-)
Thanks a lot!

**Comment by tomslominski** [comment]
Thanks. If you're using the latest version of infinity squared, you should be able to just pop your reCAPTCHA keys into `public/config.php` and the new reCAPTCHA should automatically be enabled? Just here:
https://github.com/tomslominski/infinity-squared/blob/master/public/config-sample.php#L42-L49

**Comment by Brahmachari** [comment]
Yes, this is exactly what I have done. But the recaptcha v1 with the pictures of the house numbers still appears. What can I do else? Thank you.

**Comment by Brahmachari** [comment]
Sorry, for some reason my config.php looks different. But I have downloaded it 2 days ago. I will download the complete infinity squared again.

**Comment by Brahmachari** [comment]
Well - works fine! (I have gotten infinity-squared-1.6 from some place.) Now infinity-squared-master is running perfectly.
Tom, you have done a great work. I'm very thankfull.  :-)

Do you recommend security plugins like Abusedesk or Phishtank in addition? - Probabely not?

**Comment by tomslominski** [comment]
When I tried them probably over a year ago they didn't work particularly well, but you can give them a go.
