### ISSUE TITLE
Can't create short URLs

### ISSUE THREAD

**Issue by fourlakes** [tomslominski/infinity-squared#18]
I have a simple install of YOURLS v1.7 at http://wedig.xyz and have the latest version of your files. ReCaptcha is enabled and working correctly.

But when I try to create a new keyword, I get a message saying the keyword is reserved. I am definitely using keywords that are not in the reserved words list, and have removed the advanced reserved URLs plugin to no avail.

Any thoughts?

**Comment by tomslominski** [comment]
Does that change make it work for you?

**Comment by fourlakes** [comment]
Perfect :)

Thanks!

**Comment by tomslominski** [comment]
You might want to update again, as I seem to have caused further issues while fixing this (see #19).

**Comment by fourlakes** [comment]
Have done so...works a treat. Thanks!
