### ISSUE TITLE
Please Help...

### ISSUE THREAD

**Issue by Lucianss** [tomslominski/infinity-squared#19]
I keep getting "The keyword is reserved." if I don't use a custom keyword, i'm trying to use Random Keywords plugin by Ozh but it doesn't work. Please need help urgent xDD

**Comment by tomslominski** [comment]
This was fixed in #18. Download the latest version of infinity squared and try that. :)

**Comment by Lucianss** [comment]
Downloaded it 2 days ago, so yeah, I thought it was the latest, but didn't notice you've edited a file 1 day ago, let me check that, i'll tell you if it's fixed :D

**Comment by Lucianss** [comment]
It doesn't work - http://sevo.cf

**Comment by tomslominski** [comment]
Does that work?

**Comment by Lucianss** [comment]
Yes :D
