### ISSUE TITLE
Anti-Spam

### ISSUE THREAD

**Issue by Lucianss** [tomslominski/infinity-squared#20]
How do I check if my anti-spam works?
I see I don't get reCapcha even if I have my keys from google added.

**Comment by tomslominski** [comment]
If we're talking about the same site as in your last issue, I'm seeing the reCAPTCHA thing on my devices but it says "ERROR: Invalid domain for site key". You need to make sure you enter your domain name on reCAPTCHAs site, where you got your keys from.
