### ISSUE TITLE
reCapcha hide

### ISSUE THREAD

**Issue by Lucianss** [tomslominski/infinity-squared#22]
So what code should I use to hide the button that shows the recaptcha (throught jquery) when the recaptcha is hidden, at the beggining I didn't saw recaptcha probably because I was a owner, so if that happens again I don't want a button that shows hidden content so how do I make that button dissapear when recaptcha isn't required to complete? http://sevo.cf

**Comment by tomslominski** [comment]
The same PHP code as is used here? https://github.com/tomslominski/infinity-squared/blob/master/index.php#L35-L57 The first `if` is run when the user is logged in, the second `if` is run if reCAPTCHA has been configured and the last `if` is run if the reCAPTCHA hasn't been configured. This is a custom modification of my theme, so I don't really know how it works.
