### ISSUE TITLE
Doesn't show error when shortening URL from outside of domainlimit-plugin white list

### ISSUE THREAD

**Issue by Brahmachari** [tomslominski/infinity-squared#25]
(similar to issue #23)
Prerequisite: domainlimit-plugin must be installed. 
(https://github.com/nicwaller/yourls-domainlimit-plugin)

Trying to shorten a link from a web-site that is not white listed, the theme does not show an error but shows an empty short URL box on the results page.

In addition, when the correction suggested in Issue #24 (QR-Code) has been made, whether the results page nor the footer is displayed. (Only the header is shown.)

**Comment by tomslominski** [comment]
Fixed generic empty URL errors in 87fda224620190910840e12ecf1543fa2debde42
