### ISSUE TITLE
QR-Code can not be saved nor copied

### ISSUE THREAD

**Issue by Brahmachari** [tomslominski/infinity-squared#26]
After the results page is displayed with the QR-Code as well the latter can not be saved to file nor copied to the clipboard on right click.

Looking at the code of result.php it is understandable. But looking at the situation with the eyes of a costumer it looks like being an issue.

Not only a shortened link but the QR-Code as well shall be sendable by email.

(Infinity-squared is great ! Thank you.)

**Comment by tomslominski** [comment]
I've had a very thorough look at this, and it's just not viable at the moment. Maybe when YOURLS implements a version of cron I can have another look at this, but unless you can think of how to implement this, I'll be leaving the QR codes as they are for now.

**Comment by Brahmachari** [comment]
Hi Tom
 
QR-Code, Issue #24
  _____  

Great, now it works smoothly.
 
 
QR-Code, Issue #26
  _____  

Thank you for having a look at my suggestion.
Yes, I thought of how to implement it:
 
As far as I can see one has to come away from the .svg. The <svg> does not
allow a user's right click on the chart. Using <img src="..."> makes all the
difference. That means:
 
$svgCode = QRcode::svg($dataText, $svgTagId, $saveToFile, QR_ECLEVEL_L,
$imageWidth); 
 
has to be exchanged to:
 
echo '<img src="example_001_simple_png_output.php" />';
 
View documentation:
http://phpqrcode.sourceforge.net/examples/index.php?example=202
http://phpqrcode.sourceforge.net/examples/index.php?example=002
 
I think there is no problem to deliver a pixel chart instead of a vector
chart. Better having only a .png that can be saved to file than having a
great .svg that can not be used further on.
 
 
 
Missing Error Messages, Issues #23 and #25
  _____  

More important seams to be the fact where the user is left without any error
messages. When result.php fails to execute and to be displayed, at least the
footer.php should be shown. In my case (and everybody is free to do it as
like) the footer shows a link to a help and to a contact page.
 
Would be nice when you can realise an intermediate solution.
 
 
However, those are no longer my fields of activities. My life points to
another direction.  :-)
And, however, infinit-square is great!
 
Thank you.
 
May good bless you!
Brahmachari Markus
 
 

-----Original Message-----
