### ISSUE TITLE
Feature request: Make infinity-squared protocol-relative

### ISSUE THREAD

**Issue by rkantos** [tomslominski/infinity-squared#29]
Excuse me if I've not looked thoroughly enough for a more logical or simple solution for this problem. Currently the YOURLS_SITE constant in Yourls kind of needs to have either http:// or https:// in it in order to make Yourls work properly. I know that at least currently Yourls doesn't support multi aliases. I never found the "Allow aliases" plugin mentioned here:

https://github.com/YOURLS/YOURLS/issues/1487

I already made my version of this which I have working fine; for example the favicon in header.php:
<link rel="shortcut icon" href="<?php echo preg_replace("(^https?:)","",YOURLS_SITE); ?>/images/favicon.gif" /> 

Any suggestions regarding this are also appreciated and I understand if my (non-programmer) code is unsuitable for real use..

**Comment by tomslominski** [comment]
I'm struggling to get at what exactly the issue is here. What are you trying to achieve?

**Comment by SharmileeS** [comment]
https://github.com/cnbeining/yourls-allow-aliases - is this the plugin being talked about in the above issue? I am new to yourls and unable to find a way to avoid http:// .

**Comment by tomslominski** [comment]
I'm not familiar with that plugin. Unfortunately, I can't help with issues which relate to YOURLS directly, only Infinity Squared.
