### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by eftalgezer** [tomslominski/infinity-squared#31]
https://github.com/eftalgezer/isq_translation-tr_TR
https://github.com/eftalgezer/isq_translation-fr_FR

**Comment by tomslominski** [comment]
Hi, sorry about my late reply. Thanks for contributing these!

I see you've used Loco Translate to translate these, but they seem to have exported weirdly? In the .po file, the translated strings have saved as context messages. Are you able to export these again and see if that fixes the issue?

I've reimported your Turkish translation into Loco and demonstrated this below:
<img width="283" alt="screenshot 2016-05-03 22 17 56" src="https://cloud.githubusercontent.com/assets/739599/14998698/101301a6-117d-11e6-8839-c8541e2bbf1e.png">
