### ISSUE TITLE
Feature request: Make this magic for stats-page.

### ISSUE THREAD

**Issue by Lord-Protector** [tomslominski/infinity-squared#33]
Everything looks very good, but stats page is ugly. Admin-page is not very important, because of users don't see this, but stats they could.

Вы вроде как знаете русский, или мне показалось? :)

**Comment by tomslominski** [comment]
Since the stats page is part of the admin interface, there's nothing I can do about it. However, I believe YOURLS 2.0 will include the ability to theme the admin site, so I'll deal with the admin interface & stats page then.

**Comment by tomslominski** [comment]
Also, I don't speak Russian, but at least Google Translate does 😛

**Comment by Lord-Protector** [comment]
Almost perfect translation. 
Polish to Russian Google Translate magic?..

**Comment by tomslominski** [comment]
Someone else contributed the Russian translation. I had to Google Translate your message at the top from Russian to English 😛

**Comment by Lord-Protector** [comment]
@tomslominski, okay, so just thanks this guy for this :)
