### ISSUE TITLE
reCAPTCHA

### ISSUE THREAD

**Issue by ronaldst** [tomslominski/infinity-squared#38]
There is some sort of a problem with the reCAPTCHA. I've added the proper keys in the config but no matter how or what I try, making a short link returns the error "Are you a bot? Google certainly thinks you are."

**Comment by tomslominski** [comment]
What is your site URL? Are you running any plugins?

**Comment by ronaldst** [comment]
The site is https://urldev.yourl.no

I'm not running any plugins. Have tried to fail search it but I cant figure it out. Tried in several browsers, reset cache and so on. Also tested it on my "live" site yourl.no and same issue there.

**Comment by tomslominski** [comment]
You've remembered to add your site URL to reCAPTCHA's settings here https://www.google.com/recaptcha/admin#list right?

It might be something to do with HTTPS, I'll try it on my HTTPS domain too...

**Comment by tomslominski** [comment]
It works on my HTTPS domain also. Does your host support file_get_contents()?

**Comment by ronaldst** [comment]
I've added the URL in my Google reCAPTCHA list.

It should be supported.
```
 <?php
if (function_exists('file_get_contents')) {
    echo "SUPPORT";
} else {
    echo "NO SUPPORT";
}
?>
```

Returns SUPPORT. ([https://urldev.yourl.no/test-php.php]
(https://urldev.yourl.no/test-php.php))

**Comment by ronaldst** [comment]
I set up another site on http://test.yourl.no. This is with a fresh setup of YOURLS and the only thing I edited from your files were the Google reCAPTCHA key in public/config.php. It still gives the same error, thinking I'm a robot. 

Do you got this working on your end?

**Comment by tomslominski** [comment]
Yeah, works on my host. The function would exist no matter what. I think the issue is more precisely to do with `allow_url_fopen`. Can you try the code in this post and see if that is supported? http://stackoverflow.com/questions/13433660/how-to-check-if-allow-url-fopen-is-enabled-or-not Who is your host?

**Comment by ronaldst** [comment]
You are a genius. Thank you very much.

That was the problem indeed. allow_url_fopen was not allowed in php.ini. 

I've corrected the php.ini on the server and it does indeed work as it should.

**Comment by tomslominski** [comment]
Reopening so I can do a cURL workaround for those without the ability to change their PHP settings :)
