### ISSUE TITLE
After starting qr, result.php stopped 			<!-- QR code --> 	

### ISSUE THREAD

**Issue by qy117121** [tomslominski/infinity-squared#46]
`<!-- QR code -->`
`<h2>QR code</h2>`
`<p>Share your link with external devices</p>`

The following pages cannot be run

**Comment by tomslominski** [comment]
What web server are you running and what PHP version?

**Comment by qy117121** [comment]
> What web server are you running and what PHP version?

Solved, conflict with other plug-ins, just disable the previously installed qr plugins
