### ISSUE TITLE
recaptcha not showing up

### ISSUE THREAD

**Issue by shrey2199** [tomslominski/infinity-squared#48]
![image](https://user-images.githubusercontent.com/52773351/125153334-9954f280-e170-11eb-835e-88ce64f39dcf.png)
I have defined the sitekey anf secret in config.php but recaptcha still does not show up

**Comment by tomslominski** [comment]
What's the URL of the site? If you're using reCAPTCHA v3 it might well just not be visible, but it will be working.

**Comment by shrey2199** [comment]
Ohh !! I was indeed using v3 !! Thanks for the info !! 😊😊
