### ISSUE TITLE
Unable to get recaptcha to work properly

### ISSUE THREAD

**Issue by dstyp** [tomslominski/infinity-squared#7]
Really like infinity-squared. However dealing with ton of spammers & although I got captcha showing up that can be entered the short-URL is created even if the user dont enter the captcha. The frontend renders a "captcha was incorrect message" but the database shows the entry.

**Comment by tomslominski** [comment]
As per issue #10, with the new release, reCAPTCHA issues should now be fixed. If you still have issues once the new version is released, please file another issue. Thanks :)
